'Models': {
  'logistic_regression': {
    'C': 1.0,
    'max_iter': 100,
    'solver': 'lbfgs'
  },

  'random_forest': {
    'n_estimators': 100,
    'max_depth': 3,
    'min_samples_split': 2
  },

  'Decision_tree': {
    'max_depth': 5,
    'min_samples_split': 2
  },

  'KNN': {
    'n_neighbors': 5,
    'weights': ['uniform', 'distance'],
    'metric': 'minkowski',
    'p': 2
  },

  'SVM': {
    'C': 1.0,
    'kernel': ['linear', 'poly', 'rbf', 'sigmoid'],
    'degree': 3,
    'gamma': ['scale', 'auto']
  },

  'XGBoost': {
    'n_estimators': 100,
    'max_depth': 3,
    'learning_rate': 0.1,
    'subsample': 1.0,
    'colsample_bytree': 1.0
  },

  'CatBoost': {
    'iterations': 1000,
    'learning_rate': 0.1,
    'depth': 6,
    'l2_leaf_reg': 3,
    'border_count': 32
  }
}